export const defaultCategories = [
  { id: 0, name: 'All' },
  { id: 1, name: 'Sports' },
  { id: 2, name: 'Economy' },
  { id: 3, name: 'Politics' },
  { id: 4, name: 'Technology' },
  { id: 5, name: 'Health' },
  { id: 6, name: 'World' },
];

const now = Date.now();

export const mockArticles = [
  {
    id: 101,
    title: 'Mongolian startup raises regional AI funding',
    content: 'A Ulaanbaatar-based startup closed a new round to scale AI-powered products in Central Asia.',
    author: 'news.mn',
    category: 'Technology',
    categoryId: 4,
    publishedAt: now - 1000 * 60 * 45,
    publishedDate: '45m ago',
    image: 'https://images.unsplash.com/photo-1518773553398-650c184e0bb3?w=1200',
    likesCount: 112,
    commentsCount: 22,
  },
  {
    id: 102,
    title: 'National team secures dramatic final-minute win',
    content: 'The match ended 2-1 after a late counterattack. Fans celebrated throughout the evening.',
    author: 'MNB',
    category: 'Sports',
    categoryId: 1,
    publishedAt: now - 1000 * 60 * 120,
    publishedDate: '2h ago',
    image: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200',
    likesCount: 345,
    commentsCount: 64,
  },
  {
    id: 103,
    title: 'Policy update aims to accelerate SME lending',
    content: 'New policy guidelines focus on improving access to low-interest credit for small businesses.',
    author: 'Montsame',
    category: 'Economy',
    categoryId: 2,
    publishedAt: now - 1000 * 60 * 250,
    publishedDate: '4h ago',
    image: 'https://images.unsplash.com/photo-1554224155-1696413565d3?w=1200',
    likesCount: 90,
    commentsCount: 13,
  },
  {
    id: 104,
    title: 'City launches new air quality monitoring stations',
    content: 'Real-time environmental dashboards are now available for several districts in the capital.',
    author: 'UB.info',
    category: 'Health',
    categoryId: 5,
    publishedAt: now - 1000 * 60 * 360,
    publishedDate: '6h ago',
    image: 'https://images.unsplash.com/photo-1569163139394-de4e4f43e4e3?w=1200',
    likesCount: 128,
    commentsCount: 31,
  },
  {
    id: 105,
    title: 'Regional trade talks enter final negotiation week',
    content: 'Delegations discussed tariff frameworks and logistics standards for cross-border commerce.',
    author: 'Reuters',
    category: 'World',
    categoryId: 6,
    publishedAt: now - 1000 * 60 * 720,
    publishedDate: '12h ago',
    image: 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=1200',
    likesCount: 77,
    commentsCount: 9,
  },
  {
    id: 106,
    title: 'Parliament discusses digital public service roadmap',
    content: 'The proposal includes open-data standards and faster digital identity verification.',
    author: 'Parliament Watch',
    category: 'Politics',
    categoryId: 3,
    publishedAt: now - 1000 * 60 * 960,
    publishedDate: '16h ago',
    image: 'https://images.unsplash.com/photo-1494173853739-c21f58b16055?w=1200',
    likesCount: 142,
    commentsCount: 28,
  },
];
